/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./components/ActionCard.vue')['default']
    ActionDialog: typeof import('./components/ActionDialog.vue')['default']
    AppButton: typeof import('./components/app/AppButton.vue')['default']
    AppCard: typeof import('./components/app/AppCard.vue')['default']
    AppDialog: typeof import('./components/app/AppDialog.vue')['default']
    AppEmptyState: typeof import('./components/app/AppEmptyState.vue')['default']
    AppHeader: typeof import('./components/app/AppHeader.vue')['default']
    AppHint: typeof import('./components/app/AppHint.vue')['default']
    AppInput: typeof import('./components/app/AppInput.vue')['default']
    AppPage: typeof import('./components/app/AppPage.vue')['default']
    AppSection: typeof import('./components/app/AppSection.vue')['default']
    AppSelect: typeof import('./components/app/AppSelect.vue')['default']
    AppSidebar: typeof import('./components/app/AppSidebar.vue')['default']
    AppSkeleton: typeof import('./components/app/AppSkeleton.vue')['default']
    AppStatus: typeof import('./components/app/AppStatus.vue')['default']
    AppSwitch: typeof import('./components/app/AppSwitch.vue')['default']
    AppTag: typeof import('./components/app/AppTag.vue')['default']
    AppTagsInput: typeof import('./components/app/AppTagsInput.vue')['default']
    AppTextarea: typeof import('./components/app/AppTextarea.vue')['default']
    ChannelCard: typeof import('./components/biz/ChannelCard.vue')['default']
    ChannelDialog: typeof import('./components/ChannelDialog.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    CronPicker: typeof import('./components/biz/CronPicker.vue')['default']
    DiscoveryCard: typeof import('./components/DiscoveryCard.vue')['default']
    DiscoveryDialog: typeof import('./components/DiscoveryDialog.vue')['default']
    FormDialog: typeof import('./components/biz/FormDialog.vue')['default']
    GroupDialog: typeof import('./components/GroupDialog.vue')['default']
    GroupSection: typeof import('./components/GroupSection.vue')['default']
    MonitorCard: typeof import('./components/MonitorCard.vue')['default']
    MonitorDialog: typeof import('./components/MonitorDialog.vue')['default']
    ProviderDialog: typeof import('./components/ProviderDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsForm: typeof import('./components/settings/SettingsForm.vue')['default']
    SourceCard: typeof import('./components/biz/SourceCard.vue')['default']
    SourceDialog: typeof import('./components/biz/SourceDialog.vue')['default']
    TemplateDialog: typeof import('./components/TemplateDialog.vue')['default']
    TemplateList: typeof import('./components/settings/TemplateList.vue')['default']
  }
}
