/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./components/biz/ActionCard.vue')['default']
    ActionDialog: typeof import('./components/biz/ActionDialog.vue')['default']
    AppButton: typeof import('./components/app/AppButton.vue')['default']
    AppEmptyState: typeof import('./components/app/AppEmptyState.vue')['default']
    AppHeader: typeof import('./components/app/AppHeader.vue')['default']
    AppHint: typeof import('./components/app/AppHint.vue')['default']
    AppInput: typeof import('./components/app/AppInput.vue')['default']
    AppSelect: typeof import('./components/app/AppSelect.vue')['default']
    AppSidebar: typeof import('./components/app/AppSidebar.vue')['default']
    AppSkeleton: typeof import('./components/app/AppSkeleton.vue')['default']
    AppStatus: typeof import('./components/app/AppStatus.vue')['default']
    AppSwitch: typeof import('./components/app/AppSwitch.vue')['default']
    AppTabs: typeof import('./components/app/AppTabs.vue')['default']
    AppTextarea: typeof import('./components/app/AppTextarea.vue')['default']
    ChannelCard: typeof import('./components/biz/ChannelCard.vue')['default']
    ChannelDialog: typeof import('./components/biz/ChannelDialog.vue')['default']
    ConfirmDialog: typeof import('./components/biz/ConfirmDialog.vue')['default']
    CronPicker: typeof import('./components/biz/CronPicker.vue')['default']
    ExcludeWordsField: typeof import('./components/settings/ExcludeWordsField.vue')['default']
    FormDialog: typeof import('./components/biz/FormDialog.vue')['default']
    GroupDialog: typeof import('./components/biz/GroupDialog.vue')['default']
    GroupPanel: typeof import('./components/biz/GroupPanel.vue')['default']
    MonitorCard: typeof import('./components/biz/MonitorCard.vue')['default']
    MonitorDialog: typeof import('./components/biz/MonitorDialog.vue')['default']
    ProviderDialog: typeof import('./components/biz/ProviderDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBandField: typeof import('./components/settings/ScoreBandField.vue')['default']
    SettingsForm: typeof import('./components/settings/SettingsForm.vue')['default']
    SourceCard: typeof import('./components/biz/SourceCard.vue')['default']
    SourceDialog: typeof import('./components/biz/SourceDialog.vue')['default']
    TagsField: typeof import('./components/biz/TagsField.vue')['default']
    TemplateDialog: typeof import('./components/biz/TemplateDialog.vue')['default']
    TemplateList: typeof import('./components/settings/TemplateList.vue')['default']
    ToastHost: typeof import('./components/biz/ToastHost.vue')['default']
  }
}
