/**
 * /design 这个预览页自己的文案。
 *
 * 为什么不放进 locales/*.ts：这是开发/验收页面，不在产品导航里，生产构建也不会打包。
 * 它的说明文字是给开发和验收看的，不该混进产品文案表里。产品文案仍然只活在 locales/。
 * 页面里所有可见文字都从这里取，中英各一份，切语言不该出现半截中文。
 */
const ZH = {
  // 页面本身
  'page.title': 'Design System 预览',
  'page.note':
    '开发/验收页面，不在产品导航里。下面的色值、字号、间距、圆角全部来自 design/tokens，组件全部来自 App* 组件层，页面里不写这些数值。',
  'page.viewport': '视口 {w}px · {bp} · Vuetify {v}',
  'page.sample': '示例 Aa 123',

  // 断点档
  'bp.xl': 'xl（≥1440 宽屏）',
  'bp.lg': 'lg（1280–1439）',
  'bp.md': 'md（900–1279 桌面布局）',
  'bp.sm': 'sm（600–899 大手机）',
  'bp.xs': 'xs（<600 手机）',

  'preview.colorNote': '{theme} · 语义变量',
  'preview.typeNote': '七档字号 + 行高/字重',
  'preview.spaceNote': '4px 基准的七档',
  'preview.radiusNote': '小徽标 / 控件 / 浮层 / 全圆',
  'preview.shadowNote': '只给浮层用',
  'preview.valueNote': '密度与响应式规则',
  'preview.lineHeight': '行高 · {key}',
  'preview.weight': '字重 · {key}',
  'preview.density': '密度 · {key}',
  'preview.breakpoint': '断点 · {key}',
  'preview.pageWidth': '页面宽度 · {key}',

  'states.monitor': '状态：关键词匹配 / 意图描述 / 没填关键词（全部通过）/ 仅走指定动作 / 停用',
  'demo.channelCreate.telegram': '新建 Telegram 渠道',
  'demo.channelCreate.webhook': '新建 Webhook 渠道',
  'demo.chat.me': '我自己',
  'demo.chat.group': 'Kestrel 测试群',
  'demo.monitor.dance': '舞蹈相关',
  'demo.monitor.ai': 'AI 圈动态',
  'demo.monitor.nokw': '没填关键词的监听',
  'demo.monitor.off': '已停用的监听',
  'demo.monitor.intent': '大模型发布与开源项目',

  // 分节标题
  'sec.foundation.spacing': 'Foundation · Spacing 阶梯',
  'sec.foundation.spacingNote': '只用这七档，不再出现随手写的 px',
  'sec.foundation.width': '内容宽度策略与分节：页面只声明用哪一档',
  'sec.foundation.widthNote':
    '设置、表单用 narrow；普通页 default；仪表盘与多列配置 wide；确实要占满时 full。',
  'sec.biz': '业务组件 · P1.5',
  'sec.bizNote': '从页面里沉下来的复用件：表单弹窗外壳、cron 选择器、渠道卡、数据源卡、动作卡',
  'sec.shell': '外壳：桌面常驻左栏 + 顶栏；窄屏抽屉 + 底部导航',
  'sec.shellNote':
    '你正在看的这个页面的左栏、顶栏与底部导航就是它们。桌上常驻左栏；手机上点左上角汉堡出抽屉，底部五个入口。',

  // 状态清单（这些词本身是英文的，只翻前缀）
  'states.button': '状态：default / hover / active / disabled / loading / danger',
  'states.input': '状态：default / focus / filled / disabled / readonly / error / 校验提示',
  'states.switch': '状态：on / off / disabled',
  'states.status':
    '状态色只表达状态：success / warning / error / info / neutral（另有 busy 进行中）',
  'states.card': '状态：default / interactive（整卡可点）/ disabled',
  'states.dialog': '状态：normal / loading / error / 移动端底部抽屉（<900px 自动贴底）',
  'states.formDialog': '状态：normal / 保存中(busy) / 错误 / 手机端贴底',
  'states.cron': '状态：点输入框展开生成器；表达式不合规时给报错',
  'states.channel':
    '状态：左侧色条＝渠道状态；右下角圆点＝测试连通性：未测（空心圈）→ 点一下 → 测试中（黄色转圈，不可再点）→ 连通（绿，呼吸）／有警告（黄，静止）／失败（红，静止）。停用的渠道圆点不可点；点卡片＝编辑，保存后退回未测；右上角 ×＝删除（要确认）',
  'states.source':
    '状态：状态块本身就是抓取测试的入口（还没抓过就显示「抓取测试」）；点卡片＝编辑；右上角 ×＝删除（要确认）；开关在右下；脚上只写 cron 表达式 + 下次采集时间（停用的源不显示下次）；不显示实例地址与已收条数，也不再摆底部按钮行',
  'states.action': '状态：正常 / 定时汇总 / 缺渠道 / 渠道未启用 / 停用',
  'states.hint': '语气：info / ok / warn / err',
  'states.skeleton': '版面：text / card / list / page',

  // 按钮
  'btn.primary': '主要操作',
  'btn.secondary': '次要操作',
  'btn.ghost': '弱化操作',
  'btn.smPrimary': '小号主要',
  'btn.sm': '小号',
  'btn.smGhost': '小号弱化',
  'btn.disabled': '禁用',
  'btn.disabledPrimary': '禁用主要',
  'btn.saving': '保存中',
  'btn.submitting': '提交中',
  'btn.block': '撑满宽度（弹窗底部与移动端）',

  // 卡片
  'card.variants': '变体与尺寸',
  'card.variantsNote': 'hover 与 active 用鼠标或手指直接试',
  'card.disabled': '不可用与加载',
  'card.disabledNote': 'loading 会自动禁用，避免重复提交',
  'card.input': '输入',
  'card.inputNote': 'focus 点进去看；filled 就是有值的样子',
  'card.select': '下拉',
  'card.selectNote': '选项较少时用下拉，别用长列表占地方',
  'card.switch': '开关',
  'card.status': '状态标签',
  'card.tags': '标签与计数',
  'card.tagsNote': '来源类型、启用状态、数量徽标',
  'card.surfaceType': '普通卡片',
  'card.surfaceTypeNote': '标题 + 说明 + 内容 + 卡足',
  'card.interactive': '可点卡片',
  'card.interactiveNote': '点整张卡进编辑',
  'card.off': '不可用',
  'card.offNote': '内置项或服务未连通时',
  'card.dialog': '弹窗',
  'card.dialogNote': '状态：normal / loading / error / 移动端底部抽屉（<900px 自动贴底）',
  'card.empty': '空状态',
  'card.hint': '提示条',
  'card.hintNote': '两种用法：纯说明 / 带一个动作',
  'card.section': '分节',
  'card.sectionNote': '页面内的分节：标题 + 说明 + 右侧操作',
  'card.formDialog': '表单弹窗外壳',
  'card.cron': 'cron 选择器',
  'card.channel': '通知渠道卡',
  'card.source': '数据源卡',
  'card.action': '动作卡',

  // 字段与示例值
  'field.instance': 'RSSHub 实例地址',
  'field.instanceHint': '只填实例根地址，路由路径在发现里单独填',
  'field.empty': '空值（默认态）',
  'field.filled': '已填好的值',
  'field.readonly': '只读',
  'field.readonlyHint': '这条来自模板，不能改',
  'field.errorState': '错误态',
  'field.errorMsg': '连不上这个地址（连接被拒绝）',
  'field.withAction': '带动作',
  'field.actionHint': '试抓这类动作放在输入框右侧',
  'field.judgeMode': '判定模式',
  'field.judgeHint': '灰区的处理方式',
  'field.defaultState': '默认态',
  'field.select': '请选择',
  'field.modeGone': '这个模式已经不存在了',
  'field.groupSwitch': '启用这个分组',
  'field.groupSwitchHint': '关掉后不再采集，也不会推送',
  'field.switchOn': '开关打开的样子',
  'field.builtinHint': '内置项不能改时用这一态',
  'field.summaryTime': '定时汇总时间',
  'field.summaryTimeHint': '例如 0 8 * * *',
  'field.every5': '每 5 分钟',
  'field.badCron': '写错的表达式',
  'field.every5Summary': '汇总时间',
  'field.name': '名称',
  'field.namePlaceholder': '例如：AI 圈动态',
  'field.enableNow': '立刻启用',
  'field.enableNowHint': '关掉就先存着，不采集',
  'field.actionName': '动作名称',
  'field.actionNamePlaceholder': '例如：推给 Telegram',

  // 演示数据
  'demo.mode.standard': '自带算法',
  'demo.mode.assisted': '灰区交给模型复核',
  'demo.channel.mine': '我的 Telegram',
  'demo.channel.warn': '有警告的渠道',
  'demo.channel.untested': '还没测过的渠道',
  'demo.channel.off': '停用的渠道',
  'demo.channel.fail': '连接失败的渠道',
  'demo.source.bili': 'B 站排行榜',
  'demo.source.new': '刚加的数据源',
  'demo.source.empty': '抓得到但没内容',
  'demo.source.bad': '路由写错了',
  'demo.source.off': '已停用的源',
  'demo.action.push': '推给 Telegram',
  'demo.action.digest': '早报汇总',
  'demo.action.missing': '还没选渠道的动作',
  'demo.action.off': '已停用的动作',
  'demo.action.channelOff': '渠道已停用的动作',
  'demo.trigger.realtime': '实时推送',
  'demo.trigger.digest': '定时汇总',
  'demo.channelName': '我的 Telegram',
  'demo.templateDefault': '默认模板',
  'demo.templateBrief': '简报模板',
  'demo.groupName': '新建分组',
  'demo.groupNamePlaceholder': '例如：AI 圈动态',
  'demo.bizDialogTitle': '新建动作',
  'demo.dialogTitle': '新建分组',
  'demo.saveFailed': '保存失败',
  'demo.serverError': '服务器返回 500：数据库写入失败',
  'demo.sourceStatusOk': '有内容',
  'demo.sourceStatusWarn': '抓得到但没内容',
  'demo.sourceStatusFail': '抓取失败',
  'demo.reset': '复位演示',
  'demo.rsshubConfigured': 'RSSHub 已配置',
  'demo.dialogNote':
    '在手机上打开它会从底部升起（底部抽屉，顶部圆角），桌面上是居中弹窗。关掉可以用右上角、取消按钮或 Esc。',
  'demo.formDialogNote':
    '标题、说明、取消/保存、保存中转圈、错误条、手机贴底都在这一个壳里；页面只管往里放字段。',
  'demo.emptyNote': '选一个数据源，点抓取测试看看能拿到什么',
  'demo.emptyTitle': '还没有抓过内容',
  'demo.emptyGroupTitle': '还没有分组',
  'demo.emptyGroupNote': '一个分组就是一件你关注的事',
  'demo.sectionAction': '抓取测试',
  'demo.sectionContent': '分节内容',
  'demo.embedded': '内嵌面板：卡片里再分一层时用它，别叠第二层边框',
  'demo.cardLayering': '卡片靠细边框与底色分层，不用阴影',
  'demo.cardFoot': '卡足放次要操作与说明',
  'demo.cardFootInteractive': '这一态用于配置页：整卡可点，键盘 Enter 也能进',
  'demo.cardOff': '灰掉，点不动',
  'demo.hintInfo': '普通说明：RSSHub 缓存只有 5 分钟',
  'demo.hintOk': '保存成功',
  'demo.hintWarn': '这个动作还没选渠道，命中后不会发出去',
  'demo.hintErr': '令牌不对，Telegram 返回 401',
  'demo.toast': '触发一次 Toast',
  'demo.toastNote': 'Toast 用 AppHint 的样式浮在底部，避免多一套视觉',
  'demo.tagsSource': 'RSSHub 路由',
  'demo.tagsWeb': '网页',
  'demo.badgeDiscoveries': '2 发现',
  'demo.badgeMonitors': '1 监听',
  'demo.widthFull': '不限宽',
  'demo.widthValue': 'max-width: var(--k-page-{w})',
  'demo.twoRender': 'items 同一份，两处渲染',
  'demo.dialogOpen': '打开表单弹窗',
  'demo.dialogBusy': '保存中示例',
  'demo.dialogError': '保存失败',
  'demo.toneOk': '连通，抓到 100 条',
  'demo.toneWarn': '连通但没抓到内容',
  'demo.toneErr': '连接失败',
  'demo.toneInfo': '还没试过',
  'demo.toneBusy': '测试中…',
  'demo.toneAction': '点一下试抓（action 态）',
  'demo.tonePlain': '不带状态点的纯文字徽标',
  'demo.dialogNormal': '普通弹窗',
  'demo.dialogLoading': '加载中',
  'demo.dialogErrBtn': '错误',
  'demo.layoutTextCard': 'text 与 card',
  'demo.layoutListPage': 'list 与 page',
  'demo.formDialogShellNote': '表单弹窗只管字段，标题按钮错误条都由外壳负责',
} as const

const EN: Record<keyof typeof ZH, string> = {
  'page.title': 'Design System preview',
  'page.note':
    'Dev / QA page, not part of product navigation. Every color, size, spacing and radius below comes from design/tokens, every component from the App* layer — this page writes none of those values itself.',
  'page.viewport': 'Viewport {w}px · {bp} · Vuetify {v}',
  'page.sample': 'Sample Aa 123',

  'bp.xl': 'xl (≥1440 wide)',
  'bp.lg': 'lg (1280–1439)',
  'bp.md': 'md (900–1279 desktop)',
  'bp.sm': 'sm (600–899 large phone)',
  'bp.xs': 'xs (<600 phone)',

  'preview.colorNote': '{theme} · semantic tokens',
  'preview.typeNote': 'Seven sizes + line height / weight',
  'preview.spaceNote': 'Seven steps on a 4px base',
  'preview.radiusNote': 'Small badge / control / overlay / full round',
  'preview.shadowNote': 'Overlays only',
  'preview.valueNote': 'Density and responsive rules',
  'preview.lineHeight': 'Line height · {key}',
  'preview.weight': 'Weight · {key}',
  'preview.density': 'Density · {key}',
  'preview.breakpoint': 'Breakpoint · {key}',
  'preview.pageWidth': 'Page width · {key}',

  'states.monitor':
    'States: keywords / intent / no keywords (everything passes) / limited to chosen actions / disabled',
  'demo.monitor.dance': 'Dance-related',
  'demo.monitor.ai': 'AI feed',
  'demo.monitor.nokw': 'Monitor without keywords',
  'demo.monitor.off': 'Disabled monitor',
  'demo.monitor.intent': 'Model releases and open-source projects',

  'sec.foundation.spacing': 'Foundation · Spacing scale',
  'sec.foundation.spacingNote': 'These seven steps only — no ad-hoc px',
  'sec.foundation.width': 'Content width & sections: a page only declares which step it uses',
  'sec.foundation.widthNote':
    'Settings and forms → narrow; ordinary pages → default; dashboards and multi-column config → wide; full only when it must bleed.',
  'sec.biz': 'Business components · P1.5',
  'sec.bizNote':
    'Reusable pieces lifted out of pages: form dialog shell, cron picker, channel card, source card, action card',
  'sec.shell': 'Shell: fixed left rail + top bar on desktop; drawer + bottom nav on narrow screens',
  'sec.shellNote':
    'The left rail, top bar and bottom nav of this very page are them. Fixed rail on desktop; on a phone the hamburger opens the drawer and the nav has five entries.',

  'states.button': 'States: default / hover / active / disabled / loading / danger',
  'states.input': 'States: default / focus / filled / disabled / readonly / error / validation',
  'states.switch': 'States: on / off / disabled',
  'states.status':
    'Tone only expresses state: success / warning / error / info / neutral (plus busy)',
  'states.card': 'States: default / interactive (whole card clickable) / disabled',
  'states.dialog': 'States: normal / loading / error / bottom sheet on mobile (<900px)',
  'states.formDialog': 'States: normal / saving (busy) / error / bottom sheet on mobile',
  'states.cron': 'Tap the field to open the builder; an invalid expression shows an error',
  'states.channel':
    'Left accent bar = channel state; bottom-right dot = connectivity test: untested (hollow) → tap → testing (yellow spinner, not clickable) → connected (green, pulsing) / warning (yellow, still) / failed (red, still). Disabled channels show no dot; tapping the card edits, saving resets to untested; the top-right × deletes (with confirmation)',
  'states.source':
    'The state chip is itself the fetch-test entry point (untested reads “Test fetch”); tapping the card edits; top-right × deletes (with confirmation); the switch sits bottom-right; the footer carries only the cron expression + next run (disabled sources omit the next run); no instance URL, no stored-item count, no bottom button row',
  'states.action': 'States: normal / digest / missing channel / channel off / disabled',
  'states.hint': 'States: info / ok / warn / err',
  'states.skeleton': 'Layouts: text / card / list / page',

  'btn.primary': 'Primary action',
  'btn.secondary': 'Secondary action',
  'btn.ghost': 'Quiet action',
  'btn.smPrimary': 'Small primary',
  'btn.sm': 'Small',
  'btn.smGhost': 'Small quiet',
  'btn.disabled': 'Disabled',
  'btn.disabledPrimary': 'Disabled primary',
  'btn.saving': 'Saving',
  'btn.submitting': 'Submitting',
  'btn.block': 'Full width (dialog footer, mobile)',

  'card.variants': 'Variants & sizes',
  'card.variantsNote': 'Try hover and active with mouse or finger',
  'card.disabled': 'Disabled & loading',
  'card.disabledNote': 'Loading disables the button so it cannot be submitted twice',
  'card.input': 'Text field',
  'card.inputNote': 'Focus into it; “filled” is what a value looks like',
  'card.select': 'Select',
  'card.selectNote': 'Few options → a select, not a long list',
  'card.switch': 'Switch',
  'card.status': 'Status chip',
  'card.tags': 'Tags & counts',
  'card.tagsNote': 'Source kind, enabled state, count badges',
  'card.surfaceType': 'Plain card',
  'card.surfaceTypeNote': 'Title + note + content + footer',
  'card.interactive': 'Clickable card',
  'card.interactiveNote': 'Tap the card to edit',
  'card.off': 'Unavailable',
  'card.offNote': 'Built-in items, or when the service is not reachable',
  'card.dialog': 'Dialog',
  'card.dialogNote': 'States: normal / loading / error / bottom sheet on mobile (<900px)',
  'card.empty': 'Empty state',
  'card.hint': 'Hint bar',
  'card.hintNote': 'Two uses: explanation only / with one action',
  'card.section': 'Section',
  'card.sectionNote': 'A section inside a page: title + note + trailing action',
  'card.formDialog': 'Form dialog shell',
  'card.cron': 'Cron picker',
  'card.channel': 'Notification channel card',
  'card.source': 'Source card',
  'card.action': 'Action card',

  'field.instance': 'RSSHub instance URL',
  'field.instanceHint': 'Root URL only — route paths are set on each source',
  'field.empty': 'Empty (default)',
  'field.filled': 'A filled-in value',
  'field.readonly': 'Read-only',
  'field.readonlyHint': 'Comes from a template — cannot be changed',
  'field.errorState': 'Error',
  'field.errorMsg': 'Cannot reach this address (connection refused)',
  'field.withAction': 'With action',
  'field.actionHint': 'Actions like fetch-test sit to the right of the field',
  'field.judgeMode': 'Judgement mode',
  'field.judgeHint': 'How grey areas are handled',
  'field.defaultState': 'Default',
  'field.select': 'Select…',
  'field.modeGone': 'That mode no longer exists',
  'field.groupSwitch': 'Enable this group',
  'field.groupSwitchHint': 'Off: no more collection and no notifications',
  'field.switchOn': 'Switch, on',
  'field.builtinHint': 'For built-in items that cannot be changed',
  'field.summaryTime': 'Digest time',
  'field.summaryTimeHint': 'e.g. 0 8 * * *',
  'field.every5': 'Every 5 minutes',
  'field.badCron': 'Broken expression',
  'field.every5Summary': 'Digest time',
  'field.name': 'Name',
  'field.namePlaceholder': 'e.g. my AI feed',
  'field.enableNow': 'Enable now',
  'field.enableNowHint': 'Off stores it without collecting',
  'field.actionName': 'Action name',
  'field.actionNamePlaceholder': 'e.g. push to Telegram',

  'demo.mode.standard': 'Built-in algorithm',
  'demo.mode.assisted': 'Grey areas go to the model',
  'demo.channel.mine': 'My Telegram',
  'demo.channel.warn': 'Channel with a warning',
  'demo.channel.untested': 'Never tested',
  'demo.channel.off': 'Disabled channel',
  'demo.channel.fail': 'Connection failed',
  'demo.source.bili': 'Bilibili ranking',
  'demo.source.new': 'Just added',
  'demo.source.empty': 'Reachable but empty',
  'demo.source.bad': 'Broken route',
  'demo.source.off': 'Disabled source',
  'demo.action.push': 'Push to Telegram',
  'demo.action.digest': 'Morning digest',
  'demo.action.missing': 'Action with no channel',
  'demo.action.off': 'Disabled action',
  'demo.action.channelOff': 'Action with a disabled channel',
  'demo.trigger.realtime': 'Push in real time',
  'demo.trigger.digest': 'Timed digest',
  'demo.channelName': 'My Telegram',
  'demo.templateDefault': 'Default template',
  'demo.templateBrief': 'Brief template',
  'demo.groupName': 'New group',
  'demo.groupNamePlaceholder': 'e.g. my AI feed',
  'demo.bizDialogTitle': 'New action',
  'demo.dialogTitle': 'New group',
  'demo.saveFailed': 'Save failed',
  'demo.serverError': 'Server returned 500: database write failed',
  'demo.sourceStatusOk': 'Has content',
  'demo.sourceStatusWarn': 'Reachable but empty',
  'demo.sourceStatusFail': 'Fetch failed',
  'demo.reset': 'Reset demo',
  'demo.rsshubConfigured': 'RSSHub configured',
  'demo.dialogNote':
    'On a phone it rises from the bottom (bottom sheet, rounded top); on desktop it is a centred dialog. Close it with the top-right ×, the cancel button or Esc.',
  'demo.formDialogNote':
    'Title, note, cancel/save, the saving spinner, the error bar and the mobile bottom sheet all live in this one shell; the page only supplies fields.',
  'demo.emptyNote': 'Pick a source and run the fetch test to see what comes back',
  'demo.emptyTitle': 'Nothing fetched yet',
  'demo.emptyGroupTitle': 'No groups yet',
  'demo.emptyGroupNote': 'A group is one thing you follow',
  'demo.sectionAction': 'Fetch test',
  'demo.sectionContent': 'Section content',
  'demo.embedded':
    'Embedded panel: use it for a second layer inside a card instead of nesting borders',
  'demo.cardLayering': 'Cards separate with a thin border and a tinted surface, never a shadow',
  'demo.cardFoot': 'The footer carries secondary actions and notes',
  'demo.cardFootInteractive':
    'Used on config pages: whole card clickable, keyboard Enter works too',
  'demo.cardOff': 'Greyed out, not clickable',
  'demo.hintInfo': 'Note: RSSHub caches for only 5 minutes',
  'demo.hintOk': 'Saved',
  'demo.hintWarn': 'This action has no channel, so nothing will be sent',
  'demo.hintErr': 'Bad token — Telegram returned 401',
  'demo.toast': 'Fire a toast',
  'demo.toastNote':
    'The toast borrows the AppHint look and floats at the bottom — one visual, not two',
  'demo.tagsSource': 'RSSHub route',
  'demo.tagsWeb': 'Web page',
  'demo.badgeDiscoveries': '2 sources',
  'demo.badgeMonitors': '1 watch',
  'demo.widthFull': 'unlimited',
  'demo.widthValue': 'max-width: var(--k-page-{w})',
  'demo.twoRender': 'One items array, rendered twice',
  'demo.dialogOpen': 'Open form dialog',
  'demo.dialogBusy': 'Saving example',
  'demo.dialogError': 'Save failed',
  'demo.toneOk': 'Connected, 100 items',
  'demo.toneWarn': 'Reachable but no content',
  'demo.toneErr': 'Connection failed',
  'demo.toneInfo': 'Not tested yet',
  'demo.toneBusy': 'Testing…',
  'demo.toneAction': 'Tap to fetch (action state)',
  'demo.tonePlain': 'Text-only badge, no state dot',
  'demo.channelCreate.telegram': 'New Telegram channel',
  'demo.channelCreate.webhook': 'New Webhook channel',
  'demo.chat.me': 'Myself',
  'demo.chat.group': 'Kestrel test group',
  'demo.dialogNormal': 'Plain dialog',
  'demo.dialogLoading': 'Loading',
  'demo.dialogErrBtn': 'Error',
  'demo.layoutTextCard': 'text & card',
  'demo.layoutListPage': 'list & page',
  'demo.formDialogShellNote':
    'The form dialog only carries fields — title, buttons and the error bar are the shell’s job',
}

export const DESIGN_COPY = { zh: ZH, en: EN }
export type DesignCopyKey = keyof typeof ZH

/** 取一份文案函数；调用时读 locale，切语言立刻跟着变 */
export function makeDesignCopy(locale: string) {
  const dict = locale.startsWith('en') ? EN : ZH
  return (key: DesignCopyKey, params?: Record<string, string | number>): string => {
    const text = dict[key] ?? ZH[key]
    if (!params) return text
    return text.replace(/\{(\w+)\}/g, (_match, name: string) =>
      name in params ? String(params[name]) : `{${name}}`,
    )
  }
}

/** 演示用的词表：列表型文案单独放，不塞进 string 字典 */
const ZH_LISTS = {
  'demo.monitor.keywords.dance': ['舞蹈', '街舞', 'breaking'],
  'demo.monitor.keywords.ai': ['大模型', '开源', '新版本', '评测', '论文'],
  'demo.monitor.excludes': ['广告', '二手'],
}

type DesignListKey = keyof typeof ZH_LISTS

const EN_LISTS: Record<DesignListKey, string[]> = {
  'demo.monitor.keywords.dance': ['dance', 'hip hop', 'breaking'],
  'demo.monitor.keywords.ai': ['LLM', 'open source', 'release', 'benchmark', 'paper'],
  'demo.monitor.excludes': ['ads', 'second-hand'],
}

/** 取词表；同样在调用时读 locale */
export function makeDesignLists(locale: string): (key: DesignListKey) => string[] {
  const dict = locale.startsWith('en') ? EN_LISTS : ZH_LISTS
  return (key: DesignListKey) => dict[key] ?? ZH_LISTS[key]
}
