import type { Workspace } from '@/types/domain'

/**
 * 内置示例数据。
 * 用途只有一个：在没有后端的情况下让界面结构与交互可被验收。
 * 它不代表任何真实采集、判断或发送能力 —— 界面上会明确标注「示例数据」。
 */
export const sampleWorkspace: Workspace = {
  groups: [
    {
      id: 'grp-ai-releases',
      name: 'AI 工具与模型更新',
      description: '盯模型发布、SDK 更新与厂商公告',
      enabled: true,
      revision: 3,
      cards: [
        {
          id: 'src-ai-gh',
          kind: 'source',
          name: 'GitHub Releases（3 个仓库）',
          enabled: true,
          connector: 'github',
          config: { repos: 'openai/openai-python, ollama/ollama, vllm-project/vllm' },
          cron: { expression: '*/30 * * * *' },
        },
        {
          id: 'src-ai-rsshub',
          kind: 'source',
          name: 'RSSHub：厂商博客',
          enabled: true,
          connector: 'rsshub',
          config: {
            instanceId: 'rsshub-local',
            routeId: 'anthropic/news',
            params: '',
          },
          cron: { expression: '0 */2 * * *' },
        },
        {
          id: 'wch-model-updates',
          kind: 'watcher',
          name: '模型发布 / 版本更新',
          enabled: true,
          sourceIds: ['src-ai-gh', 'src-ai-rsshub'],
          focus: '新模型或新版本发布',
          include: ['发布', 'release', 'v\\d+\\.\\d+'],
          exclude: ['招聘', '赞助'],
          operator: 'any',
          llmEnabled: true,
          llmProfileId: 'llm-local',
          fallbackEnabled: true,
          actionIds: ['act-ai-push'],
        },
        {
          id: 'act-ai-push',
          kind: 'action',
          name: '即时推送到 Telegram',
          enabled: true,
          trigger: 'instant',
          channelId: 'ch-telegram',
          template: '{{title}}\n{{url}}',
        },
      ],
    },
    {
      id: 'grp-nas-infra',
      name: 'NAS 与自托管服务',
      description: '容器更新、镜像发布与安全公告',
      enabled: true,
      revision: 1,
      cards: [
        {
          id: 'src-nas-gh',
          kind: 'source',
          name: 'GitHub Releases（自托管项目）',
          enabled: true,
          connector: 'github',
          config: { repos: 'jxxghp/MoviePilot, navidrome/navidrome' },
          cron: { expression: '0 */6 * * *' },
        },
        {
          id: 'wch-releases',
          kind: 'watcher',
          name: '新版本发布',
          enabled: true,
          sourceIds: ['src-nas-gh'],
          focus: '新版本与破坏性变更',
          include: ['v\\d+\\.\\d+\\.\\d+'],
          exclude: ['nightly'],
          operator: 'any',
          llmEnabled: false,
          fallbackEnabled: true,
          actionIds: ['act-nas-digest'],
        },
        {
          id: 'act-nas-digest',
          kind: 'action',
          name: '每天汇总到企业微信',
          enabled: false,
          trigger: 'digest',
          channelId: 'ch-wecom',
          template: '今日更新：\n{{items}}',
          cron: { expression: '0 21 * * *' },
        },
      ],
    },
    {
      id: 'grp-media-library',
      name: '媒体库与下载',
      description: '订阅更新与下载完成后的整理提示',
      enabled: false,
      revision: 1,
      cards: [
        {
          id: 'src-media-rss',
          kind: 'source',
          name: '站点 RSS',
          enabled: false,
          connector: 'rss',
          config: { url: 'https://example.invalid/feed.xml' },
          cron: { expression: '0 */12 * * *' },
        },
        {
          id: 'wch-media-new',
          kind: 'watcher',
          name: '新条目',
          enabled: false,
          sourceIds: ['src-media-rss'],
          focus: '新条目更新',
          include: [],
          exclude: [],
          operator: 'any',
          llmEnabled: false,
          fallbackEnabled: true,
          actionIds: [],
        },
      ],
    },
  ],
  channels: [
    {
      id: 'ch-telegram',
      name: 'Telegram Bot',
      type: 'telegram',
      enabled: true,
      capabilities: { instant: true, digest: true },
      credentialStatus: 'configured',
    },
    {
      id: 'ch-wecom',
      name: '企业微信应用',
      type: 'wecom',
      enabled: true,
      capabilities: { instant: false, digest: true },
      credentialStatus: 'configured',
    },
    {
      id: 'ch-webhook',
      name: '通用 Webhook',
      type: 'webhook',
      enabled: false,
      capabilities: { instant: true, digest: false },
      credentialStatus: 'unset',
    },
  ],
  llmProfiles: [
    {
      id: 'llm-local',
      name: '本地 Ollama',
      type: 'ollama',
      enabled: true,
      credentialStatus: 'configured',
    },
  ],
  rsshubInstances: [
    {
      id: 'rsshub-local',
      name: '本机 RSSHub',
      baseUrl: 'http://localhost:1200',
      enabled: true,
      catalogStatus: 'unknown',
    },
  ],
  settings: {
    timezone: 'Asia/Shanghai',
    retryLimit: 3,
    requestTimeoutSeconds: 20,
    retentionDays: 90,
  },
}
